<form action="https://www.sandbox.paypal.com/webapps/adaptivepayment/flow/pay" target="PPDGFrame" class="standard">
	<input type="image" id="submitBtn" value="Process Order">
	<input id="type" type="hidden" name="expType" value="light">
	<input id="paykey" type="hidden" name="paykey" value="AP-0Y146284RV262752L">
</form>

<?php echo $token; ?>

<script src="https://www.paypalobjects.com/js/external/dg.js" type="text/javascript"></script>
<script type="text/javascript" charset="utf-8">
	var embeddedPPFlow = new PAYPAL.apps.DGFlow({trigger: 'submitBtn'});
</script>