<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Checkup Motor Parts Admin')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php 
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet('http://cdn.sencha.com/ext/gpl/5.0.0/build/packages/ext-theme-crisp/build/resources/ext-theme-crisp-all.css');
        ?>

        <style type="text/css">
            /*.default-icon {
              background-image: url("../img/zf2-logo.png");
              background-repeat: no-repeat;
            }

            body {
                overflow : hidden !important;
            }

            #panel-main-body {
                overflow: auto !important;
                margin: 0 auto !important;
                width : 100%;
            }

            #Administration-Users-panel-body {
                height  : 275px !important;
            }

            #Administration-Users-panel #toolbar-1054 {
                top  : 300px !important;
            }*/
        </style>
        

    </head>
    <body>

        <div id="container"></div>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile('http://cdn.sencha.com/ext/gpl/5.0.0/build/ext-all.js')
            ->prependFile($this->basePath() . '/js/helper.js')
            ->prependFile($this->basePath() . '/js/lib/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/lib/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',)); 
        ?>

        <?php echo $this->content; ?>
    </body>
</html>
