<style type="text/css">
   /* #panel-main .x-panel-header,
    #panel-main .x-toolbar,
    #panel-main #panel-main-body {
        width   : 100% !important;
    }

    .x-livesearch-match {
        font-weight: bold;
        background-color: yellow;
    }*/

    .x-tool-mytool {
        /*background-image: url(<?php echo $this->basePath() . '/img/favicon.ico'; ?>) !important;*/
    }  
</style>
<script type="text/javascript">
  <?php echo $this->headScript()->prependFile($this->basePath() . '/js/Panel.js'); 
    ?>
</script>