<style type="text/css">
   /* .x-panel-header,
    .x-tab-bar,
    #tabpanel-main-body {
        width   : 298px !important;
    }

    #ext-comp-1009
    {
        margin: 0 auto !important;
        top : 150px;
    }

    .x-livesearch-match {
        font-weight: bold;
        background-color: yellow;
    }*/

    .x-tool-mytool {
        /*background-image: url(<?php echo $this->basePath() . '/img/favicon.ico'; ?>) !important;*/
    } 

    /*#txt-username-inputEl,
    #txt-password-inputEl
    {
        width : 97% !important;
    }*/

    /*#cbo-store-login-bodyEl.x-form-item-body
    {
        width: 156px !important;
        right : 4px !important;
    }*/

    /*#login-window {
        height : 163px !important;
        width : 300px !important;
    }

    #login-window-body {
        height: 133px !important;
    }

    #ext-gen1038
    {
        height : 159px !important;
        width : 300px !important;
    }

    #login-window_header
    {
        width : 300px !important;
    }

    #ext-gen1038.x-mask
    {
        display : none;
    }

    #ext-gen1039.x-css-shadow {
        width : 300px !important;
        height : 159px !important;
    }*/
</style>
<script type="text/javascript">
    Ext.create('Checkup.Login.Form.Login', {token : '<?php echo $token;?>'});
</script>